language: node_js
node_js:
 - "8"
 - "node"
install: yarn install --ignore-scripts
script:
  - yarn run lint
  - yarn run build
  - yarn run production
cache:
  yarn: true
  directories:
    - node_modules
